name: ✨ Feature Request
description: Suggest a feature for us to implement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
      placeholder: "Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you're requesting.
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem-solved
    attributes:
      label: Problem This Feature Solves
      description: Describe the problem or limitation you're facing that this feature would address.
      placeholder: What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe any alternatives you've considered...

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: Explain how this feature would benefit users of Shopstr.
      placeholder: How would this feature benefit users?
    validations:
      required: true

  - type: textarea
    id: relevant-nips
    attributes:
      label: Relevant NIPs
      description: If this feature relates to specific Nostr Implementation Possibilities (NIPs), list them here.
      placeholder: "e.g. NIP-01, NIP-04, etc."

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have ideas about how to implement this feature, share them here.
      placeholder: Share any implementation ideas you might have...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Mockups
      description: If applicable, add screenshots, diagrams, or mockups to help explain your feature request.
      placeholder: Drag and drop your images here or click to upload...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
      placeholder: Any additional context that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true