name: 🔒 Security Vulnerability
description: Report a security vulnerability to fix
title: "[SECURITY] "
labels: ["security"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT SECURITY NOTICE ⚠️**
        
        We take security vulnerabilities seriously. Thank you for your responsible disclosure. 
        We will work to address the issue promptly and keep you informed of our progress.
        
        Please provide as much detail as possible to help us understand and fix the vulnerability.

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability you've identified.
      placeholder: Describe the security vulnerability...
    validations:
      required: true

  - type: dropdown
    id: impact-level
    attributes:
      label: Impact Level
      description: How severe do you consider this vulnerability to be?
      options:
        - Critical - Immediate action required
        - High - Significant security risk
        - Medium - Moderate security risk
        - Low - Minor security concern
        - Informational - Security best practice
    validations:
      required: true

  - type: textarea
    id: impact-description
    attributes:
      label: Impact
      description: Describe the potential impact of this vulnerability (e.g., data exposure, financial loss, privacy breach).
      placeholder: What could happen if this vulnerability is exploited?
    validations:
      required: true

  - type: checkboxes
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the application are affected?
      options:
        - Authentication
        - Payment processing
        - Messaging system
        - User data handling
        - API endpoints
        - File uploads/downloads
        - Session management
        - Database queries
        - Other (specify in additional context)

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps To Reproduce
      description: Clear steps to reproduce the vulnerability
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe '...'
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have ideas on how to address this vulnerability, please share them here.
      placeholder: How do you think this should be fixed?

  - type: dropdown
    id: device-type
    attributes:
      label: Device
      description: What device were you using when you discovered this vulnerability?
      options:
        - Desktop
        - Mobile (Android)
        - Mobile (iPhone)
        - Tablet
        - Other

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system were you using?
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - iOS
        - Android
        - Other

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Mobile Browser
        - Other

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of the application were you using?
      placeholder: "e.g. 0.1.0"

  - type: textarea
    id: related-nips
    attributes:
      label: Related NIPs
      description: If this security issue relates to specific Nostr Implementation Possibilities (NIPs), list them here.
      placeholder: "e.g. NIP-01, NIP-04, etc."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant to understanding or fixing the vulnerability.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: disclosure-agreement
    attributes:
      label: Responsible Disclosure Agreement
      description: Please confirm your understanding of responsible disclosure
      options:
        - label: I understand this is a security vulnerability and agree to responsible disclosure practices
          required: true
        - label: I have not publicly disclosed this vulnerability elsewhere
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true